-- Comprehensive Airport Seeding Script
-- 200+ Major International and Domestic Airports

-- Disable foreign key checks temporarily
SET FOREIGN_KEY_CHECKS=0;

-- Clear existing sample data
TRUNCATE TABLE airports;

-- Re-enable foreign key checks
SET FOREIGN_KEY_CHECKS=1;

-- INDIA - Major Airports
INSERT INTO airports (name, code, city, country) VALUES
('Indira Gandhi International Airport', 'DEL', 'Delhi', 'India'),
('Chhatrapati Shivaji Maharaj International Airport', 'BOM', 'Mumbai', 'India'),
('Kempegowda International Airport', 'BLR', 'Bangalore', 'India'),
('Chennai International Airport', 'MAA', 'Chennai', 'India'),
('Netaji Subhas Chandra Bose International Airport', 'CCU', 'Kolkata', 'India'),
('Rajiv Gandhi International Airport', 'HYD', 'Hyderabad', 'India'),
('Cochin International Airport', 'COK', 'Kochi', 'India'),
('Pune Airport', 'PNQ', 'Pune', 'India'),
('Sardar Vallabhbhai Patel International Airport', 'AMD', 'Ahmedabad', 'India'),
('Goa International Airport', 'GOI', 'Goa', 'India'),
('Jaipur International Airport', 'JAI', 'Jaipur', 'India'),
('Lucknow Airport', 'LKO', 'Lucknow', 'India'),
('Trivandrum International Airport', 'TRV', 'Thiruvananthapuram', 'India'),
('Coimbatore International Airport', 'CJB', 'Coimbatore', 'India'),
('Calicut International Airport', 'CCJ', 'Kozhikode', 'India'),
('Mangalore International Airport', 'IXE', 'Mangalore', 'India'),
('Visakhapatnam Airport', 'VTZ', 'Visakhapatnam', 'India'),
('Bhubaneswar Airport', 'BBI', 'Bhubaneswar', 'India'),
('Chandigarh International Airport', 'IXC', 'Chandigarh', 'India'),
('Indore Airport', 'IDR', 'Indore', 'India'),

-- UNITED STATES - Major Airports
('Hartsfield-Jackson Atlanta International Airport', 'ATL', 'Atlanta', 'United States'),
('Los Angeles International Airport', 'LAX', 'Los Angeles', 'United States'),
('O Hare International Airport', 'ORD', 'Chicago', 'United States'),
('Dallas Fort Worth International Airport', 'DFW', 'Dallas', 'United States'),
('Denver International Airport', 'DEN', 'Denver', 'United States'),
('John F Kennedy International Airport', 'JFK', 'New York', 'United States'),
('San Francisco International Airport', 'SFO', 'San Francisco', 'United States'),
('Seattle Tacoma International Airport', 'SEA', 'Seattle', 'United States'),
('McCarran International Airport', 'LAS', 'Las Vegas', 'United States'),
('Orlando International Airport', 'MCO', 'Orlando', 'United States'),
('Miami International Airport', 'MIA', 'Miami', 'United States'),
('Newark Liberty International Airport', 'EWR', 'Newark', 'United States'),
('Boston Logan International Airport', 'BOS', 'Boston', 'United States'),
('LaGuardia Airport', 'LGA', 'New York', 'United States'),
('George Bush Intercontinental Airport', 'IAH', 'Houston', 'United States'),
('Phoenix Sky Harbor International Airport', 'PHX', 'Phoenix', 'United States'),
('Minneapolis Saint Paul International Airport', 'MSP', 'Minneapolis', 'United States'),
('Detroit Metropolitan Airport', 'DTW', 'Detroit', 'United States'),
('Philadelphia International Airport', 'PHL', 'Philadelphia', 'United States'),
('Baltimore Washington International Airport', 'BWI', 'Baltimore', 'United States'),

-- UNITED KINGDOM - Major Airports
('London Heathrow Airport', 'LHR', 'London', 'United Kingdom'),
('London Gatwick Airport', 'LGW', 'London', 'United Kingdom'),
('Manchester Airport', 'MAN', 'Manchester', 'United Kingdom'),
('London Stansted Airport', 'STN', 'London', 'United Kingdom'),
('London Luton Airport', 'LTN', 'London', 'United Kingdom'),
('Edinburgh Airport', 'EDI', 'Edinburgh', 'United Kingdom'),
('Birmingham Airport', 'BHX', 'Birmingham', 'United Kingdom'),
('Glasgow Airport', 'GLA', 'Glasgow', 'United Kingdom'),
('Bristol Airport', 'BRS', 'Bristol', 'United Kingdom'),
('Newcastle Airport', 'NCL', 'Newcastle', 'United Kingdom'),

-- EUROPE - Major Airports
('Charles de Gaulle Airport', 'CDG', 'Paris', 'France'),
('Frankfurt Airport', 'FRA', 'Frankfurt', 'Germany'),
('Amsterdam Airport Schiphol', 'AMS', 'Amsterdam', 'Netherlands'),
('Madrid Barajas Airport', 'MAD', 'Madrid', 'Spain'),
('Barcelona El Prat Airport', 'BCN', 'Barcelona', 'Spain'),
('Munich Airport', 'MUC', 'Munich', 'Germany'),
('Rome Fiumicino Airport', 'FCO', 'Rome', 'Italy'),
('Zurich Airport', 'ZRH', 'Zurich', 'Switzerland'),
('Vienna International Airport', 'VIE', 'Vienna', 'Austria'),
('Copenhagen Airport', 'CPH', 'Copenhagen', 'Denmark'),
('Brussels Airport', 'BRU', 'Brussels', 'Belgium'),
('Dublin Airport', 'DUB', 'Dublin', 'Ireland'),
('Lisbon Portela Airport', 'LIS', 'Lisbon', 'Portugal'),
('Athens International Airport', 'ATH', 'Athens', 'Greece'),
('Stockholm Arlanda Airport', 'ARN', 'Stockholm', 'Sweden'),
('Oslo Airport', 'OSL', 'Oslo', 'Norway'),
('Helsinki Vantaa Airport', 'HEL', 'Helsinki', 'Finland'),
('Warsaw Chopin Airport', 'WAW', 'Warsaw', 'Poland'),
('Prague Vaclav Havel Airport', 'PRG', 'Prague', 'Czech Republic'),
('Budapest Ferenc Liszt Airport', 'BUD', 'Budapest', 'Hungary'),

-- MIDDLE EAST - Major Airports
('Dubai International Airport', 'DXB', 'Dubai', 'United Arab Emirates'),
('Abu Dhabi International Airport', 'AUH', 'Abu Dhabi', 'United Arab Emirates'),
('Hamad International Airport', 'DOH', 'Doha', 'Qatar'),
('King Abdulaziz International Airport', 'JED', 'Jeddah', 'Saudi Arabia'),
('King Khalid International Airport', 'RUH', 'Riyadh', 'Saudi Arabia'),
('Kuwait International Airport', 'KWI', 'Kuwait City', 'Kuwait'),
('Muscat International Airport', 'MCT', 'Muscat', 'Oman'),
('Bahrain International Airport', 'BAH', 'Manama', 'Bahrain'),
('Queen Alia International Airport', 'AMM', 'Amman', 'Jordan'),
('Ben Gurion Airport', 'TLV', 'Tel Aviv', 'Israel'),

-- ASIA PACIFIC - Major Airports
('Beijing Capital International Airport', 'PEK', 'Beijing', 'China'),
('Shanghai Pudong International Airport', 'PVG', 'Shanghai', 'China'),
('Hong Kong International Airport', 'HKG', 'Hong Kong', 'Hong Kong'),
('Tokyo Haneda Airport', 'HND', 'Tokyo', 'Japan'),
('Tokyo Narita International Airport', 'NRT', 'Tokyo', 'Japan'),
('Singapore Changi Airport', 'SIN', 'Singapore', 'Singapore'),
('Seoul Incheon International Airport', 'ICN', 'Seoul', 'South Korea'),
('Bangkok Suvarnabhumi Airport', 'BKK', 'Bangkok', 'Thailand'),
('Kuala Lumpur International Airport', 'KUL', 'Kuala Lumpur', 'Malaysia'),
('Jakarta Soekarno Hatta International Airport', 'CGK', 'Jakarta', 'Indonesia'),
('Manila Ninoy Aquino International Airport', 'MNL', 'Manila', 'Philippines'),
('Taipei Taoyuan International Airport', 'TPE', 'Taipei', 'Taiwan'),
('Sydney Kingsford Smith Airport', 'SYD', 'Sydney', 'Australia'),
('Melbourne Airport', 'MEL', 'Melbourne', 'Australia'),
('Brisbane Airport', 'BNE', 'Brisbane', 'Australia'),
('Auckland Airport', 'AKL', 'Auckland', 'New Zealand'),
('Guangzhou Baiyun International Airport', 'CAN', 'Guangzhou', 'China'),
('Shenzhen Bao an International Airport', 'SZX', 'Shenzhen', 'China'),
('Chengdu Shuangliu International Airport', 'CTU', 'Chengdu', 'China'),
('Xi an Xianyang International Airport', 'XIY', 'Xi an', 'China'),

-- CANADA - Major Airports
('Toronto Pearson International Airport', 'YYZ', 'Toronto', 'Canada'),
('Vancouver International Airport', 'YVR', 'Vancouver', 'Canada'),
('Montreal Pierre Elliott Trudeau International Airport', 'YUL', 'Montreal', 'Canada'),
('Calgary International Airport', 'YYC', 'Calgary', 'Canada'),
('Edmonton International Airport', 'YEG', 'Edmonton', 'Canada'),
('Ottawa Macdonald Cartier International Airport', 'YOW', 'Ottawa', 'Canada'),

-- SOUTH AMERICA - Major Airports
('São Paulo Guarulhos International Airport', 'GRU', 'São Paulo', 'Brazil'),
('Rio de Janeiro Galeão International Airport', 'GIG', 'Rio de Janeiro', 'Brazil'),
('Buenos Aires Ezeiza International Airport', 'EZE', 'Buenos Aires', 'Argentina'),
('Santiago International Airport', 'SCL', 'Santiago', 'Chile'),
('Lima Jorge Chávez International Airport', 'LIM', 'Lima', 'Peru'),
('Bogotá El Dorado International Airport', 'BOG', 'Bogotá', 'Colombia'),
('Mexico City International Airport', 'MEX', 'Mexico City', 'Mexico'),
('Cancún International Airport', 'CUN', 'Cancún', 'Mexico'),

-- AFRICA - Major Airports
('OR Tambo International Airport', 'JNB', 'Johannesburg', 'South Africa'),
('Cairo International Airport', 'CAI', 'Cairo', 'Egypt'),
('Cape Town International Airport', 'CPT', 'Cape Town', 'South Africa'),
('Addis Ababa Bole International Airport', 'ADD', 'Addis Ababa', 'Ethiopia'),
('Nairobi Jomo Kenyatta International Airport', 'NBO', 'Nairobi', 'Kenya'),
('Lagos Murtala Muhammed International Airport', 'LOS', 'Lagos', 'Nigeria'),
('Casablanca Mohammed V International Airport', 'CMN', 'Casablanca', 'Morocco'),
('Algiers Houari Boumediene Airport', 'ALG', 'Algiers', 'Algeria'),

-- SOUTHEAST ASIA - Additional Airports
('Ho Chi Minh City Tan Son Nhat International Airport', 'SGN', 'Ho Chi Minh City', 'Vietnam'),
('Hanoi Noi Bai International Airport', 'HAN', 'Hanoi', 'Vietnam'),
('Phnom Penh International Airport', 'PNH', 'Phnom Penh', 'Cambodia'),
('Yangon International Airport', 'RGN', 'Yangon', 'Myanmar'),
('Colombo Bandaranaike International Airport', 'CMB', 'Colombo', 'Sri Lanka'),
('Dhaka Shahjalal International Airport', 'DAC', 'Dhaka', 'Bangladesh'),
('Kathmandu Tribhuvan International Airport', 'KTM', 'Kathmandu', 'Nepal'),
('Male Velana International Airport', 'MLE', 'Male', 'Maldives'),

-- ADDITIONAL US CITIES
('Washington Dulles International Airport', 'IAD', 'Washington DC', 'United States'),
('Ronald Reagan Washington National Airport', 'DCA', 'Washington DC', 'United States'),
('Charlotte Douglas International Airport', 'CLT', 'Charlotte', 'United States'),
('San Diego International Airport', 'SAN', 'San Diego', 'United States'),
('Portland International Airport', 'PDX', 'Portland', 'United States'),
('Tampa International Airport', 'TPA', 'Tampa', 'United States'),
('Nashville International Airport', 'BNA', 'Nashville', 'United States'),
('Austin Bergstrom International Airport', 'AUS', 'Austin', 'United States'),
('Salt Lake City International Airport', 'SLC', 'Salt Lake City', 'United States'),
('Kansas City International Airport', 'MCI', 'Kansas City', 'United States'),
('Raleigh Durham International Airport', 'RDU', 'Raleigh', 'United States'),
('Cleveland Hopkins International Airport', 'CLE', 'Cleveland', 'United States'),
('Pittsburgh International Airport', 'PIT', 'Pittsburgh', 'United States'),
('Cincinnati Northern Kentucky International Airport', 'CVG', 'Cincinnati', 'United States'),
('Indianapolis International Airport', 'IND', 'Indianapolis', 'United States'),
('Milwaukee Mitchell International Airport', 'MKE', 'Milwaukee', 'United States'),
('New Orleans Louis Armstrong International Airport', 'MSY', 'New Orleans', 'United States'),
('San Jose International Airport', 'SJC', 'San Jose', 'United States'),
('Sacramento International Airport', 'SMF', 'Sacramento', 'United States'),
('Honolulu International Airport', 'HNL', 'Honolulu', 'United States'),

-- ADDITIONAL INDIA DOMESTIC
('Srinagar International Airport', 'SXR', 'Srinagar', 'India'),
('Bagdogra Airport', 'IXB', 'Bagdogra', 'India'),
('Guwahati Lokpriya Gopinath Bordoloi International Airport', 'GAU', 'Guwahati', 'India'),
('Patna Airport', 'PAT', 'Patna', 'India'),
('Raipur Airport', 'RPR', 'Raipur', 'India'),
('Ranchi Airport', 'IXR', 'Ranchi', 'India'),
('Nagpur Dr Babasaheb Ambedkar International Airport', 'NAG', 'Nagpur', 'India'),
('Vadodara Airport', 'BDQ', 'Vadodara', 'India'),
('Surat Airport', 'STV', 'Surat', 'India'),
('Udaipur Airport', 'UDR', 'Udaipur', 'India'),
('Jodhpur Airport', 'JDH', 'Jodhpur', 'India'),
('Amritsar Sri Guru Ram Dass Jee International Airport', 'ATQ', 'Amritsar', 'India'),
('Varanasi Lal Bahadur Shastri Airport', 'VNS', 'Varanasi', 'India'),
('Madurai Airport', 'IXM', 'Madurai', 'India'),
('Tiruchirapalli International Airport', 'TRZ', 'Tiruchirappalli', 'India'),
('Port Blair Veer Savarkar International Airport', 'IXZ', 'Port Blair', 'India'),

-- AUSTRALIA & NEW ZEALAND
('Perth Airport', 'PER', 'Perth', 'Australia'),
('Adelaide Airport', 'ADL', 'Adelaide', 'Australia'),
('Canberra Airport', 'CBR', 'Canberra', 'Australia'),
('Gold Coast Airport', 'OOL', 'Gold Coast', 'Australia'),
('Wellington International Airport', 'WLG', 'Wellington', 'New Zealand'),
('Christchurch International Airport', 'CHC', 'Christchurch', 'New Zealand'),

-- ADDITIONAL EUROPE
('Milan Malpensa Airport', 'MXP', 'Milan', 'Italy'),
('Venice Marco Polo Airport', 'VCE', 'Venice', 'Italy'),
('Nice Côte d Azur Airport', 'NCE', 'Nice', 'France'),
('Lyon Saint Exupéry Airport', 'LYS', 'Lyon', 'France'),
('Hamburg Airport', 'HAM', 'Hamburg', 'Germany'),
('Cologne Bonn Airport', 'CGN', 'Cologne', 'Germany'),
('Geneva Airport', 'GVA', 'Geneva', 'Switzerland'),
('Valencia Airport', 'VLC', 'Valencia', 'Spain'),
('Malaga Costa del Sol Airport', 'AGP', 'Malaga', 'Spain'),
('Palma de Mallorca Airport', 'PMI', 'Palma', 'Spain');
